package IHM;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class Login {
    private JPanel panel1;
    private JTextField usernameTextField;
    private JButton loginButton;
    private JLabel Logo;
    private JPanel logopan;
    private JPanel username;

    public Login() {
        loginButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

            }
        });
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("Clavardage");
        frame.setContentPane(new Login().panel1);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        panel1.setPreferredSize(new Dimension(400, 415));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new BorderLayout(0, 5));
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.insets = new Insets(20, 20, 70, 20);
        panel1.add(panel2, gbc);
        username = new JPanel();
        username.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        username.setMinimumSize(new Dimension(150, 24));
        username.setPreferredSize(new Dimension(200, 24));
        panel2.add(username, BorderLayout.NORTH);
        final JLabel label1 = new JLabel();
        label1.setText("User");
        username.add(label1);
        usernameTextField = new JTextField();
        usernameTextField.setHorizontalAlignment(0);
        usernameTextField.setMinimumSize(new Dimension(70, 24));
        usernameTextField.setPreferredSize(new Dimension(150, 24));
        usernameTextField.setText("");
        usernameTextField.setToolTipText("Username");
        username.add(usernameTextField);
        loginButton = new JButton();
        loginButton.setMargin(new Insets(10, 5, 5, 10));
        loginButton.setMaximumSize(new Dimension(80, 32));
        loginButton.setMinimumSize(new Dimension(40, 32));
        loginButton.setPreferredSize(new Dimension(50, 32));
        loginButton.setText("Login");
        panel2.add(loginButton, BorderLayout.CENTER);
        logopan = new JPanel();
        logopan.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(40, 40, 40, 40);
        panel1.add(logopan, gbc);
        logopan.setBorder(BorderFactory.createTitledBorder("put logo here*"));
        Logo = new JLabel();
        Logo.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        logopan.add(Logo, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
