package IHM;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import Controller.Controller;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

public class Login {
    private JPanel panel1;
    private JTextField usernameTextField;
    private JButton loginButton;
    private JPanel logopanel;
    private JPanel username;
    private JLabel errorMessage;
    private Controller controller;

    public Login(Controller controller) {
        this.controller = controller;
        JLabel logo = new JLabel(new ImageIcon("image/logo.jpg"));
        logopanel.add(logo);
        errorMessage.setVisible(false);
        loginButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Try to connect with nickname here
                String nickname = usernameTextField.getText();
                if (nickname != null) // can add restriction here
                    controller.login(nickname);
            }
        });
    }

    public void show_error() {
        errorMessage.setVisible(true);
    }

    public JPanel getPanel1() {
        return panel1;
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        panel1.setEnabled(true);
        panel1.setPreferredSize(new Dimension(400, 415));
        logopanel = new JPanel();
        logopanel.setLayout(new GridBagLayout());
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 2;
        gbc.gridheight = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(40, 40, 40, 40);
        panel1.add(logopanel, gbc);
        logopanel.setBorder(BorderFactory.createTitledBorder(""));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(panel2, gbc);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new BorderLayout(0, 5));
        panel2.add(panel3, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        username = new JPanel();
        username.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        username.setMinimumSize(new Dimension(150, 24));
        username.setPreferredSize(new Dimension(200, 24));
        panel3.add(username, BorderLayout.NORTH);
        final JLabel label1 = new JLabel();
        label1.setText("User");
        username.add(label1);
        usernameTextField = new JTextField();
        usernameTextField.setHorizontalAlignment(0);
        usernameTextField.setMinimumSize(new Dimension(70, 24));
        usernameTextField.setPreferredSize(new Dimension(150, 24));
        usernameTextField.setText("");
        usernameTextField.setToolTipText("Username");
        username.add(usernameTextField);
        loginButton = new JButton();
        loginButton.setMargin(new Insets(10, 5, 5, 10));
        loginButton.setMaximumSize(new Dimension(80, 32));
        loginButton.setMinimumSize(new Dimension(40, 32));
        loginButton.setPreferredSize(new Dimension(50, 32));
        loginButton.setText("Login");
        panel3.add(loginButton, BorderLayout.CENTER);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel2.add(panel4, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 20), null, 0, false));
        errorMessage = new JLabel();
        errorMessage.setEnabled(true);
        errorMessage.setForeground(new Color(-4515310));
        errorMessage.setText("Your username is already taken");
        panel4.add(errorMessage, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel1.add(spacer1, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
